sudo : required
services:
  - docker
before_install:
  - docker build -t backend/server -f Dockerfile.dev
script:
  -docker run backend/server npm test -- --coverage
  # - docker run -e CI=true backend/server npm run test

after_success:
  - docker build -t backend/server .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push backend/server